name: text_file_translator # Or your project name
description: A new Flutter project.
publish_to: 'none' # Remove this line if you intend to publish the package

version: 1.0.0+1

environment:
  sdk: '^3.0.0' # Example: Use a recent stable SDK constraint, like ^3.3.0 or as suggested by flutter doctor
  flutter: '>=1.17.0' # Or your current Flutter version constraint

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0 # Or latest version
  file_picker: ^8.0.0 # Or latest version (check pub.dev if you upgraded/downgraded)
  file_selector: ^1.0.3 # Or latest version
  collection: ^1.18.0 # Or latest version
  google_fonts: ^6.2.1 # Or latest version
  shimmer: ^3.0.0 # Or latest version
  share_plus: ^9.0.0 # Or latest version (if you upgraded, use that version)
  flutter_tts: ^4.0.2 # Or latest version
  provider: ^6.1.2 # Or latest version (for theme management)
  # If you decide to use flutter_dotenv for API key:
  # flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Or latest version

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg